site_name: Cinder + Superhero

theme:
    name: null
    custom_dir: 'cinder-superhero'

site_author: Christopher Simpkins, Michael Christen
site_description: "A Superhero-modified version of Cinder"
repo_url: "https://github.com/chrissimpkins/cinder"

nav:
  - Home: index.md
  - Cinder: cinder.md
  - Specimen: specimen.md

markdown_extensions:
  - admonition
